docker load -i traefik.tar 
docker load -i certbot.tar 
docker load -i openmrs.tar 
docker load -i mysql.tar 
docker load -i openhim-core.tar 
docker load -i openhim-console.tar 
docker load -i openhim-config.tar 
docker load -i opencr1.tar 
docker load -i hapi1.tar 
docker load -i elasticsearch.tar 
docker load -i zookeeper.tar 
docker load -i kafka.tar 
docker load -i wait-for-openmrs-action.tar 
docker load -i openmrs-fhir-analytics.tar 
docker load -i postman.tar 
docker load -i certgen.tar 
docker load -i postgres.tar 
docker load -i openelis-global.tar 
docker load -i hapi2.tar 
docker load -i mongo.tar
docker load -i opencr2.tar